run:
  timeout: 5m
  skip-files: [ ]
  skip-dirs: [ ]

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 13
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
      - github.com/pkg/errors
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - httpNoBody
      - sloppyReassign
      - hugeParam
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
  gosec:
    excludes:
      - G304 # Potential file inclusion via variable
      - G307 # Deferring unsafe method "Close" on type "\*os.File"

linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - execinquery # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - gomnd
    - tparallel
    - paralleltest
    - testpackage
    - goerr113
    - wrapcheck
    - nlreturn
    - wsl
    - exhaustive
    - exhaustruct
    - noctx
    - varnamelen
    - nilnil
    - contextcheck
    - nonamedreturns
    - forcetypeassert

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'package-comments: should have a package comment'
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - nosnakecase
    - path: pkg/core/scrapper.go
      text: Function 'process' is too long
    - path: pkg/core/scrapper.go
      text: Function 'process' has too many statements
    - path: pkg/core/scrapper.go
      text: 'cyclomatic complexity \d+ of func `\(\*Scrapper\).process` is high'
    - path: pkg/sources/github.go
      text: 'G110: Potential DoS vulnerability via decompression bomb'
