run:
  timeout: 5m
  skip-files: [ ]
  skip-dirs: [ ]

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - httpNoBody
      - sloppyReassign
      - hugeParam
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
      - unnamedResult
      - whyNoLint # already handle by nonolint

  gosec:
    excludes:
      - G304 # Potential file inclusion via variable
      - G307 # Deferring unsafe method "Close" on type "\*os.File"
  gomoddirectives:
    replace-allow-list:
      - github.com/http-wasm/http-wasm-host-go

  tagalign:
    align: false
    sort: true
    order:
      - description
      - json
      - toml
      - yaml
      - yml
      - label
      - label-slice-as-struct
      - file
      - kv
      - export

linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - execinquery # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - ireturn
    - lll
    - dupl
    - gomnd
    - tparallel
    - paralleltest
    - testpackage
    - goerr113
    - wrapcheck
    - nlreturn
    - wsl
    - exhaustive
    - exhaustruct
    - noctx
    - varnamelen
    - nilnil
    - contextcheck
    - nonamedreturns
    - forcetypeassert
    - prealloc
    - mnd

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'package-comments: should have a package comment'
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - nosnakecase
    - path: pkg/core/scrapper.go
      text: Function 'process' is too long
    - path: pkg/core/scrapper.go
      text: Function 'process' has too many statements
    - path: pkg/core/scrapper.go
      text: 'cyclomatic complexity \d+ of func `\(\*Scrapper\).process` is high'
    - path: pkg/sources/github.go
      text: 'G110: Potential DoS vulnerability via decompression bomb'
    - path: pkg/tracer/tracer.go
      text: 'Setup returns interface \(go\.opentelemetry\.io/otel/sdk/trace.SpanProcessor\)'
