[run]
  deadline = "2m"
  skip-files = []

[linters-settings]

  [linters-settings.govet]
    check-shadowing = true

  [linters-settings.gocyclo]
    min-complexity = 16.0

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 3.0

  [linters-settings.misspell]
    locale = "US"

  [linters-settings.godox]
    keywords = ["FIXME"]

[linters]
  enable-all = true
  disable = [
    "interfacer", # deprecated
    "maligned", # deprecated
    "scopelint", # deprecated
    "sqlclosecheck", # Not relevant (SQL)
    "rowserrcheck", # Not relevant (SQL)
    "cyclop", # Duplicate of gocyclo
    "lll",
    "gosec",
    "dupl",
    "gomnd",
    "tparallel",
    "paralleltest",
    "testpackage",
    "goerr113",
    "wrapcheck",
    "nlreturn",
    "wsl",
    "exhaustive",
    "exhaustivestruct",
    "ifshort",
    "noctx",
  ]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same-issues = 0
  exclude = [
    "ST1000: at least one file in a package should have a package comment"
  ]

  [[issues.exclude-rules]]
    path = "(.+)_test.go"
    linters = ["goconst", "funlen", "godot"]

  [[issues.exclude-rules]]
    path = "sources-github.go"
    linters = ["gosec","nestif"]

  [[issues.exclude-rules]]
    path = "pkg/core/scrapper.go"
    text = "Function 'process' is too long"

  [[issues.exclude-rules]]
    path = "pkg/core/scrapper.go"
    text = "Function 'process' has too many statements"
